AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Storefront static hosting
Parameters:
  DNSZone:
    Type: String
    Description: The Route 53 Hosted Zone Id to use for storefront. First create and register a hosted zone with parent DNS.
  HostName:
    Type: String
    Description: The domain name for the Storefront. This must be a subdomain of the hosted DNS zone.
Resources: