  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${HostName}-storefront-site'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  