  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'Distribuição CloudFront para ${HostName}'
        DefaultRootObject: index.html
        Aliases:
          - !Ref HostName
        DefaultCacheBehavior:
          TargetOriginId: StaticSiteBucketOrigin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        Origins:
          - DomainName: !GetAtt StaticSiteBucket.DomainName
            Id: StaticSiteBucketOrigin
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOAI}'
        ViewerCertificate:
          AcmCertificateArn: !Ref NetworkSSLCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2019
  NetworkDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref DNSZone
      Name: !Ref HostName
      Type: CNAME
      TTL: 300
      ResourceRecords:
        - !GetAtt CloudFrontDistribution.DomainName
  